#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_PARTMOD                             100
#define IDD_CREATE                              102
#define IDD_FORMAT                              103
#define IAC_ACCELERATOR                         105
#define IDD_DISKIMAGE                           115
#define IDR_MENU                                117
#define IDD_BACKUP                              119
#define IDD_SAVE_PROGRESS                       121
#define IDD_CHECK_DISK                          125
#define CHK_NTFS_COMPRESS                       1000
#define EDT_FILENAME                            1000
#define IDB_FS_CHECK                            1001
#define IDR_GPT_HOLDER                          1001
#define IDT_DESCRIPTION                         1001
#define ILV_ERROR_LIST                          1001
#define IDT_CURRENT_SECTOR                      1002
#define EDT_SIZE                                1003
#define IDB_FIX_SELECTED                        1003
#define IDT_SECTORS_TOTAL                       1003
#define EDT_BPS                                 1004
#define IDR_PRIMARY                             1004
#define IDT_MIDDLE_TEXT                         1004
#define IDB_FIX_ALL                             1005
#define IDP_PROGRESS                            1005
#define IDR_GPT                                 1005
#define CMB_FS                                  1007
#define IDB_REFRESH                             1007
#define EDT_SPT                                 1008
#define EDT_TPC                                 1009
#define EDT_CYLINDERS                           1010
#define CMB_CLUSTER_SIZE                        1011
#define IDB_BROWSE                              1011
#define CHK_QUICKFMT                            1013
#define IDB_DISKIMAGE                           1013
#define IDC_EDIT1                               1015
#define IDA_DELETE                              40000
#define IDB_ABOUT                               40000
#define IDB_BACKUP_CREATE                       40001
#define IDB_CLOSE_DISK                          40002
#define IDB_BACKUP_RESTORE                      40003
#define IDB_SET_INACTIVE                        40004
#define IDB_FORMAT                              40005
#define IDB_CHECK_DISK                          40006
#define IDB_WIPE                                40008
#define ILV_PHYSICAL                            40020
#define ILV_LOGICAL                             40021
#define IDB_NEWPART                             40022
#define IDB_DELETE                              40023
#define IDB_RESIZE                              40026
#define IDB_BS_MOD                              40028
#define IDR_EXTENDED                            40030
#define IDR_LOGICAL                             40031
#define IDB_SAVE                                40032
#define CMB_SIZE                                40035
#define IDB_SET_ACTIVE                          40036
